# Generated by Django 4.2.5 on 2023-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
